<?php

namespace FernleafSystems\ApiWrappers\Email\SendInBlue\Account;

use FernleafSystems\ApiWrappers\Email\SendInBlue\Api;

class Retrieve extends Api {

	const REQUEST_METHOD = 'get';

	protected function getVO() :AccountVO {
		return new AccountVO(); // TODO: Change the autogenerated stub
	}

	protected function getUrlEndpoint() :string {
		return 'account';
	}
}