<?php

namespace FernleafSystems\ApiWrappers\Email\SendInBlue\Users;

/**
 * Class Retrieve
 * @package FernleafSystems\ApiWrappers\Email\SendInBlue\Users
 */
class Retrieve extends Delete {

	const REQUEST_METHOD = 'get';

	/**
	 * @param string $sEmail
	 * @return MemberVO|null
	 */
	public function byEmail( $sEmail ) {
		return $this->setEmail( $sEmail )
					->asVo();
	}

	/**
	 * @return MemberVO
	 */
	protected function getVO() {
		return new MemberVO(); // TODO: Change the autogenerated stub
	}
}