<?php

namespace FernleafSystems\ApiWrappers\Email\SendInBlue\Users;

/**
 * Class Retrieve
 * @package FernleafSystems\ApiWrappers\Email\SendInBlue\Users
 */
class Retrieve extends Delete {

	const REQUEST_METHOD = 'get';

	/**
	 * @param string $email
	 * @return MemberVO|null
	 */
	public function byEmail( $email ) {
		return $this->setEmail( $email )
					->asVo();
	}

	protected function getVO() :MemberVO {
		return new MemberVO(); // TODO: Change the autogenerated stub
	}
}